### ISSUE TITLE
`URLPatternList` defined in source but not exported in dist

### ISSUE THREAD

**Issue by bennypowers** [kenchris/urlpattern-polyfill#36] opened 2021-08-29 11:09 UTC
```ts
import { URLPatternList } from 'https://unpkg.com/urlpattern-polyfill@1.0.0-rc1/dist/index.js?module';
```
> import not found: URLPatternList

Indeed, it's defined in `/src`, but not in `/dist`

**Comment by kenchris** [comment] 2021-08-29 11:10
@wanderview what is the spec status of URLPatternList?

**Comment by wanderview** [comment] 2021-08-30 14:04
We haven't figured out the API yet and I think it may change from the original based on feedback I got on ordering, finding the best route in a set, etc.  See [here](https://github.com/WICG/urlpattern/issues/30#issuecomment-897109588).

I would recommend removing it from the polyfill for now.  I intend to work on it further after we get the initial API shipped.

**Comment by bennypowers** [comment] 2021-08-30 15:34
Thanks for the feedback @wanderview 

FYI my case is your typical SPA router but this time its Lit ReactiveControllers. The service worker stuff is super cool, but i'm not focused on that atm.

Thanks for working on this v. nifty spec

**Comment by wanderview** [comment] 2021-08-30 15:47
If you have time, it would help if you posted in the [spec issue](https://github.com/WICG/urlpattern/issues/30#issuecomment-897109588) what kind of features you need out of the list.  Does it need to be supported, have fast lookup, etc?  How do you define "best match"?  Sorting by particular URL components?  This kind of feedback will help us figure out a reasonable API shape.

**Comment by kenchris** [comment] 2022-03-31 11:56
Closing as this was on purpose. Maybe we should remove the code

**Closed as completed by kenchris** 2022-03-31 11:56 UTC

**Comment by hax** [comment] 2023-06-14 06:07
It seems chrome already land `URLPatternList` behind the flag. So maybe it's the time to reopen the issue?

**Comment by kenchris** [comment] 2023-06-14 06:55
@hax does it have WPT test cases we can use to make sure it works as intended?
